-- Employee & Vendor Data Analytics Project
-- File: 06_employee_performance_comparison.sql
-- Description: Employee performance comparison: London vs. rest of company
-- Tools: Microsoft SQL Server Management Studio (SSMS)
-- Author: Prashna Dhakal
-- Date: 2025-11-04
-- ------------------------------------------------------------
-- Business Context:
-- The HR and Sales departments requested an analysis to
-- assess the performance of UK-based sales employees versus
-- the rest of the company. This helps inform staffing and
-- potential expansion decisions.
-- ------------------------------------------------------------

-- 1️⃣ Number of London-based Employees
SELECT COUNT(*) AS NumEmployeesInLondon
FROM Employees
WHERE City = 'London';
-- Purpose: Determines size of the UK sales team.

-- ------------------------------------------------------------

-- 2️⃣ Orders generated by London Employees
SELECT EmployeeID, CustomerID, OrderID, OrderDate
FROM Orders
WHERE EmployeeID IN (
    SELECT EmployeeID
    FROM Employees
    WHERE City = 'London'
)
ORDER BY EmployeeID, CustomerID, OrderDate DESC;
-- Purpose: Lists all orders by UK employees for further analysis.

-- ------------------------------------------------------------

-- 3️⃣ Employee Productivity Metrics (London)
SELECT EmployeeID, 
       COUNT(OrderID) AS TotOrders,
       SUM(OrderNetRevenue) AS TotNetRev,
       AVG(OrderNetRevenue) AS NetRevPerOrder
FROM Orders
WHERE EmployeeID IN (
    SELECT EmployeeID
    FROM Employees
    WHERE City = 'London'
)
GROUP BY EmployeeID;
-- Purpose: Measures individual productivity of UK sales reps.

-- ------------------------------------------------------------

-- 4️⃣ Combined UK Productivity (averaged per employee)
SELECT 'United Kingdom' AS Geography,
       COUNT(DISTINCT EmployeeID) AS NumEmployees,
       COUNT(OrderID) AS TotOrders,
       COUNT(OrderID) / COUNT(DISTINCT EmployeeID) AS NumOrdersPerEmp,
       SUM(OrderNetRevenue) AS TotNetRev,
       SUM(OrderNetRevenue) / COUNT(DISTINCT EmployeeID) AS NetRevPerEmp,
       SUM(OrderNetRevenue) / COUNT(OrderID) AS NetRevPerOrder
FROM Orders
WHERE EmployeeID IN (
    SELECT EmployeeID
    FROM Employees
    WHERE City = 'London'
);

-- ------------------------------------------------------------

-- 5️⃣ Productivity for the rest of the company
SELECT 'Balance Of Company' AS Geography,
       COUNT(DISTINCT EmployeeID) AS NumEmployees,
       COUNT(OrderID) AS TotOrders,
       COUNT(OrderID) / COUNT(DISTINCT EmployeeID) AS NumOrdersPerEmp,
       SUM(OrderNetRevenue) AS TotNetRev,
       SUM(OrderNetRevenue) / COUNT(DISTINCT EmployeeID) AS NetRevPerEmp,
       AVG(OrderNetRevenue) AS NetRevPerOrder
FROM Orders
WHERE EmployeeID NOT IN (
    SELECT EmployeeID
    FROM Employees
    WHERE City = 'London'
);
-- Purpose: Enables comparison of productivity between regions.

-- ------------------------------------------------------------

-- 6️⃣ Extra Credit: Using EXISTS instead of IN
SELECT EmployeeID, 
       COUNT(OrderID) AS TotOrders,
       SUM(OrderNetRevenue) AS TotNetRev,
       AVG(OrderNetRevenue) AS NetRevPerOrder
FROM Orders
WHERE EXISTS(
    SELECT 1
    FROM Employees
    WHERE Employees.EmployeeID = Orders.EmployeeID
      AND City = 'London'
)
GROUP BY EmployeeID;

-- ------------------------------------------------------------

-- ✅ End of file
